name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'
  DOCKER_REGISTRY: docker.io

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run tests with coverage
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        pytest tests/ -v --tb=short --cov=src --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Check code formatting (optional)
      continue-on-error: true
      run: |
        pip install black isort
        black --check src/ tests/
        isort --check-only src/ tests/

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile
        target: runtime-base  # Build only the base runtime for testing
        push: false
        tags: doc-intel:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
    
    - name: Test Docker image
      run: |
        docker run --rm doc-intel:test python /app/scripts/health_check.py

  docker-push:
    name: Push to Docker Hub
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile
        target: runtime-base  # Only build and push the base runtime (402MB)
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/document-intelligence-ai:latest
          ${{ secrets.DOCKER_USERNAME }}/document-intelligence-ai:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy flake8 bandit
    
    - name: Run linters
      continue-on-error: true
      run: |
        echo "Running flake8..."
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        
        echo "Running pylint..."
        pylint src/ --disable=all --enable=W0102,W0613,W0614 || true
        
        echo "Running mypy..."
        mypy src/ --ignore-missing-imports || true
    
    - name: Security check with bandit
      continue-on-error: true
      run: |
        bandit -r src/ -f json -o bandit-report.json || true
        if [ -f bandit-report.json ]; then
          cat bandit-report.json
        fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'CRITICAL,HIGH'
        format: 'table'
        exit-code: '0'  # Don't fail the build on vulnerabilities
    
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./